"""
Extended vocabulary data - 1000+ words across multiple languages
This file contains comprehensive vocabulary lists for A1, A2, B1 levels
"""

# English Vocabulary by Category and Level
ENGLISH_VOCABULARY = {
    "A1": {
        "Numbers": [
            ("one", "bir", "wʌn", "number", "The number 1", "I have one apple."),
            ("two", "iki", "tuː", "number", "The number 2", "She has two cats."),
            ("three", "üç", "θriː", "number", "The number 3", "There are three books."),
            ("four", "dört", "fɔː", "number", "The number 4", "I need four chairs."),
            ("five", "beş", "faɪv", "number", "The number 5", "Five people are here."),
            ("six", "altı", "sɪks", "number", "The number 6", "It's six o'clock."),
            ("seven", "yedi", "ˈsevn", "number", "The number 7", "I work seven days."),
            ("eight", "sekiz", "eɪt", "number", "The number 8", "Eight hours of sleep."),
            ("nine", "dokuz", "naɪn", "number", "The number 9", "Nine students passed."),
            ("ten", "on", "ten", "number", "The number 10", "Ten fingers on my hands."),
        ],
        "Colors": [
            ("red", "kırmızı", "red", "adjective", "Color of blood", "I have a red car."),
            ("blue", "mavi", "bluː", "adjective", "Color of sky", "The sky is blue."),
            ("green", "yeşil", "ɡriːn", "adjective", "Color of grass", "Trees are green."),
            ("yellow", "sarı", "ˈjeləʊ", "adjective", "Color of sun", "Yellow flowers bloom."),
            ("black", "siyah", "blæk", "adjective", "Darkest color", "Black coffee, please."),
            ("white", "beyaz", "waɪt", "adjective", "Lightest color", "White snow falls."),
            ("orange", "turuncu", "ˈɒrɪndʒ", "adjective", "Mix of red and yellow", "Orange juice is fresh."),
            ("purple", "mor", "ˈpɜːpl", "adjective", "Mix of red and blue", "Purple flowers are beautiful."),
            ("brown", "kahverengi", "braʊn", "adjective", "Color of wood", "Brown shoes match."),
            ("pink", "pembe", "pɪŋk", "adjective", "Light red", "Pink roses smell nice."),
        ],
        "Family": [
            ("mother", "anne", "ˈmʌðə", "noun", "Female parent", "My mother is kind."),
            ("father", "baba", "ˈfɑːðə", "noun", "Male parent", "My father works hard."),
            ("sister", "kız kardeş", "ˈsɪstə", "noun", "Female sibling", "I have one sister."),
            ("brother", "erkek kardeş", "ˈbrʌðə", "noun", "Male sibling", "My brother is tall."),
            ("grandmother", "büyükanne", "ˈɡrænmʌðə", "noun", "Mother's mother", "Grandmother makes cookies."),
            ("grandfather", "büyükbaba", "ˈɡrænfɑːðə", "noun", "Father's father", "Grandfather tells stories."),
            ("daughter", "kız", "ˈdɔːtə", "noun", "Female child", "She is my daughter."),
            ("son", "oğul", "sʌn", "noun", "Male child", "He is my son."),
            ("aunt", "teyze/hala", "ɑːnt", "noun", "Parent's sister", "My aunt visits often."),
            ("uncle", "amca/dayı", "ˈʌŋkl", "noun", "Parent's brother", "Uncle plays with us."),
        ],
        "Body Parts": [
            ("head", "baş", "hed", "noun", "Top part of body", "My head hurts."),
            ("eye", "göz", "aɪ", "noun", "Organ for seeing", "Blue eyes are beautiful."),
            ("nose", "burun", "nəʊz", "noun", "Organ for smelling", "I have a big nose."),
            ("mouth", "ağız", "maʊθ", "noun", "Organ for eating/speaking", "Open your mouth wide."),
            ("ear", "kulak", "ɪə", "noun", "Organ for hearing", "My ears are cold."),
            ("hand", "el", "hænd", "noun", "Body part for holding", "Wash your hands."),
            ("foot", "ayak", "fʊt", "noun", "Body part for walking", "My feet are tired."),
            ("leg", "bacak", "leɡ", "noun", "Lower limb", "Long legs run fast."),
            ("arm", "kol", "ɑːm", "noun", "Upper limb", "Strong arms lift heavy."),
            ("finger", "parmak", "ˈfɪŋɡə", "noun", "Part of hand", "Ten fingers to count."),
        ],
        "Time": [
            ("today", "bugün", "təˈdeɪ", "noun", "This day", "Today is Monday."),
            ("yesterday", "dün", "ˈjestədeɪ", "noun", "Day before today", "Yesterday was Sunday."),
            ("tomorrow", "yarın", "təˈmɒrəʊ", "noun", "Day after today", "Tomorrow is Tuesday."),
            ("morning", "sabah", "ˈmɔːnɪŋ", "noun", "Early part of day", "Good morning everyone."),
            ("afternoon", "öğleden sonra", "ˌɑːftəˈnuːn", "noun", "After noon", "Good afternoon sir."),
            ("evening", "akşam", "ˈiːvnɪŋ", "noun", "End of day", "Good evening folks."),
            ("night", "gece", "naɪt", "noun", "Dark hours", "Good night sleep well."),
            ("week", "hafta", "wiːk", "noun", "Seven days", "One week vacation."),
            ("month", "ay", "mʌnθ", "noun", "~30 days", "Next month travels."),
            ("year", "yıl", "jɪə", "noun", "12 months", "Happy new year!"),
        ],
        "Weather": [
            ("sun", "güneş", "sʌn", "noun", "Star giving light", "The sun is bright."),
            ("rain", "yağmur", "reɪn", "noun", "Water falling", "Rain is falling now."),
            ("snow", "kar", "snəʊ", "noun", "Frozen rain", "Snow covers ground."),
            ("wind", "rüzgar", "wɪnd", "noun", "Moving air", "Strong wind blows."),
            ("cloud", "bulut", "klaʊd", "noun", "Water vapor mass", "Clouds hide sun."),
            ("hot", "sıcak", "hɒt", "adjective", "High temperature", "Summer is hot."),
            ("cold", "soğuk", "kəʊld", "adjective", "Low temperature", "Winter is cold."),
            ("warm", "ılık", "wɔːm", "adjective", "Pleasant heat", "Spring is warm."),
            ("cool", "serin", "kuːl", "adjective", "Slightly cold", "Autumn is cool."),
            ("weather", "hava", "ˈweðə", "noun", "Atmospheric condition", "Nice weather today."),
        ],
        "Animals": [
            ("dog", "köpek", "dɒɡ", "noun", "Domestic pet", "Dog is friendly."),
            ("cat", "kedi", "kæt", "noun", "Feline pet", "Cat is sleeping."),
            ("bird", "kuş", "bɜːd", "noun", "Flying animal", "Bird sings beautifully."),
            ("fish", "balık", "fɪʃ", "noun", "Water animal", "Fish swims fast."),
            ("horse", "at", "hɔːs", "noun", "Large animal", "Horse runs quickly."),
            ("cow", "inek", "kaʊ", "noun", "Farm animal", "Cow gives milk."),
            ("pig", "domuz", "pɪɡ", "noun", "Farm animal", "Pig is pink."),
            ("chicken", "tavuk", "ˈtʃɪkɪn", "noun", "Farm bird", "Chicken lays eggs."),
            ("sheep", "koyun", "ʃiːp", "noun", "Wool animal", "Sheep is white."),
            ("rabbit", "tavşan", "ˈræbɪt", "noun", "Small animal", "Rabbit hops around."),
        ],
        "House": [
            ("house", "ev", "haʊs", "noun", "Building to live in", "House is big."),
            ("room", "oda", "ruːm", "noun", "Part of house", "Room is clean."),
            ("kitchen", "mutfak", "ˈkɪtʃɪn", "noun", "Cooking room", "Kitchen is modern."),
            ("bathroom", "banyo", "ˈbɑːθruːm", "noun", "Washing room", "Bathroom is small."),
            ("bedroom", "yatak odası", "ˈbedruːm", "noun", "Sleeping room", "Bedroom is cozy."),
            ("door", "kapı", "dɔː", "noun", "Entrance", "Door is open."),
            ("window", "pencere", "ˈwɪndəʊ", "noun", "Glass opening", "Window is closed."),
            ("table", "masa", "ˈteɪbl", "noun", "Furniture surface", "Table is wooden."),
            ("chair", "sandalye", "tʃeə", "noun", "Sitting furniture", "Chair is comfortable."),
            ("bed", "yatak", "bed", "noun", "Sleeping furniture", "Bed is soft."),
        ],
        "Clothing": [
            ("shirt", "gömlek", "ʃɜːt", "noun", "Upper garment", "Shirt is white."),
            ("pants", "pantolon", "pænts", "noun", "Lower garment", "Pants are blue."),
            ("dress", "elbise", "dres", "noun", "One-piece garment", "Dress is beautiful."),
            ("shoes", "ayakkabı", "ʃuːz", "noun", "Footwear", "Shoes are new."),
            ("socks", "çorap", "sɒks", "noun", "Foot covering", "Socks are warm."),
            ("hat", "şapka", "hæt", "noun", "Head covering", "Hat is red."),
            ("coat", "palto", "kəʊt", "noun", "Outer garment", "Coat is thick."),
            ("jacket", "ceket", "ˈdʒækɪt", "noun", "Short coat", "Jacket is stylish."),
            ("skirt", "etek", "skɜːt", "noun", "Lower garment", "Skirt is long."),
            ("sweater", "kazak", "ˈswetə", "noun", "Warm top", "Sweater is cozy."),
        ],
        "Actions": [
            ("walk", "yürümek", "wɔːk", "verb", "Move on foot", "I walk daily."),
            ("run", "koşmak", "rʌn", "verb", "Move fast", "Children run fast."),
            ("eat", "yemek", "iːt", "verb", "Consume food", "We eat dinner."),
            ("drink", "içmek", "drɪŋk", "verb", "Consume liquid", "I drink water."),
            ("sleep", "uyumak", "sliːp", "verb", "Rest", "Baby sleeps well."),
            ("talk", "konuşmak", "tɔːk", "verb", "Speak", "They talk loudly."),
            ("listen", "dinlemek", "ˈlɪsn", "verb", "Hear attentively", "Students listen carefully."),
            ("read", "okumak", "riːd", "verb", "Look at text", "I read books."),
            ("write", "yazmak", "raɪt", "verb", "Make text", "She writes letters."),
            ("play", "oynamak", "pleɪ", "verb", "Have fun", "Kids play outside."),
        ],
    },
    "A2": {
        "Emotions": [
            ("angry", "kızgın", "ˈæŋɡri", "adjective", "Feeling mad", "I am angry."),
            ("excited", "heyecanlı", "ɪkˈsaɪtɪd", "adjective", "Very enthusiastic", "She is excited."),
            ("worried", "endişeli", "ˈwʌrid", "adjective", "Feeling anxious", "He is worried."),
            ("surprised", "şaşırmış", "səˈpraɪzd", "adjective", "Feeling shock", "They are surprised."),
            ("bored", "sıkılmış", "bɔːd", "adjective", "Not interested", "I am bored."),
            ("scared", "korkmuş", "skeəd", "adjective", "Feeling fear", "Cat is scared."),
            ("proud", "gururlu", "praʊd", "adjective", "Feeling satisfied", "I am proud."),
            ("jealous", "kıskanç", "ˈdʒeləs", "adjective", "Wanting what others have", "He is jealous."),
            ("nervous", "sinirli", "ˈnɜːvəs", "adjective", "Feeling tense", "I am nervous."),
            ("confident", "kendinden emin", "ˈkɒnfɪdənt", "adjective", "Self-assured", "She is confident."),
            ("happy", "mutlu", "ˈhæpi", "adjective", "Feeling joy", "I am happy today."),
            ("sad", "üzgün", "sæd", "adjective", "Feeling sorrow", "She feels sad."),
            ("tired", "yorgun", "ˈtaɪəd", "adjective", "Needing rest", "I am very tired."),
            ("relaxed", "rahat", "rɪˈlækst", "adjective", "Calm and peaceful", "He feels relaxed."),
            ("stressed", "stresli", "strest", "adjective", "Under pressure", "Work makes me stressed."),
        ],
        "Jobs": [
            ("teacher", "öğretmen", "ˈtiːtʃə", "noun", "Person who teaches", "Teacher explains well."),
            ("doctor", "doktor", "ˈdɒktə", "noun", "Medical professional", "Doctor helps patients."),
            ("nurse", "hemşire", "nɜːs", "noun", "Medical assistant", "Nurse is caring."),
            ("engineer", "mühendis", "ˌendʒɪˈnɪə", "noun", "Technical professional", "Engineer designs bridges."),
            ("lawyer", "avukat", "ˈlɔːjə", "noun", "Legal professional", "Lawyer defends clients."),
            ("cook", "aşçı", "kʊk", "noun", "Person who cooks", "Cook makes delicious food."),
            ("waiter", "garson", "ˈweɪtə", "noun", "Restaurant server", "Waiter serves quickly."),
            ("driver", "sürücü", "ˈdraɪvə", "noun", "Person who drives", "Driver is careful."),
            ("police", "polis", "pəˈliːs", "noun", "Law enforcement", "Police keep safe."),
            ("artist", "sanatçı", "ˈɑːtɪst", "noun", "Creative person", "Artist paints beautifully."),
            ("pilot", "pilot", "ˈpaɪlət", "noun", "Person who flies planes", "Pilot flies internationally."),
            ("musician", "müzisyen", "mjuːˈzɪʃn", "noun", "Person who makes music", "Musician plays guitar."),
            ("scientist", "bilim insanı", "ˈsaɪəntɪst", "noun", "Person who does research", "Scientist discovers new things."),
            ("manager", "yönetici", "ˈmænɪdʒə", "noun", "Person who manages", "Manager leads the team."),
            ("accountant", "muhasebeci", "əˈkaʊntənt", "noun", "Person who handles finances", "Accountant checks numbers."),
        ],
        "Places": [
            ("school", "okul", "skuːl", "noun", "Place of learning", "Children go to school."),
            ("hospital", "hastane", "ˈhɒspɪtl", "noun", "Medical facility", "Hospital treats sick people."),
            ("bank", "banka", "bæŋk", "noun", "Financial institution", "Bank keeps money safe."),
            ("library", "kütüphane", "ˈlaɪbrəri", "noun", "Book collection", "Library has many books."),
            ("museum", "müze", "mjuːˈziːəm", "noun", "Art/history place", "Museum shows old art."),
            ("park", "park", "pɑːk", "noun", "Public garden", "Park has green grass."),
            ("beach", "plaj", "biːtʃ", "noun", "Sandy shore", "Beach is beautiful."),
            ("mountain", "dağ", "ˈmaʊntən", "noun", "High land", "Mountain is tall."),
            ("river", "nehir", "ˈrɪvə", "noun", "Flowing water", "River is wide."),
            ("forest", "orman", "ˈfɒrɪst", "noun", "Many trees", "Forest is green."),
            ("restaurant", "restoran", "ˈrestrɒnt", "noun", "Place to eat", "Restaurant serves Italian food."),
            ("cafe", "kafe", "kæˈfeɪ", "noun", "Coffee shop", "Cafe has good coffee."),
            ("supermarket", "süpermarket", "ˈsuːpəmɑːkɪt", "noun", "Large store", "Supermarket sells groceries."),
            ("airport", "havalimanı", "ˈeəpɔːt", "noun", "Place for flights", "Airport is crowded today."),
            ("station", "istasyon", "ˈsteɪʃn", "noun", "Train or bus stop", "Station is near here."),
        ],
        "Food": [
            ("bread", "ekmek", "bred", "noun", "Baked food", "Fresh bread smells good."),
            ("cheese", "peynir", "tʃiːz", "noun", "Dairy product", "Cheese is delicious."),
            ("meat", "et", "miːt", "noun", "Animal flesh", "Meat is cooking now."),
            ("fish", "balık", "fɪʃ", "noun", "Aquatic animal", "Fish is healthy food."),
            ("rice", "pirinç", "raɪs", "noun", "Grain food", "Rice is popular worldwide."),
            ("pasta", "makarna", "ˈpæstə", "noun", "Italian noodles", "Pasta with tomato sauce."),
            ("salad", "salata", "ˈsæləd", "noun", "Mixed vegetables", "Salad is very fresh."),
            ("soup", "çorba", "suːp", "noun", "Liquid food", "Soup warms you up."),
            ("fruit", "meyve", "fruːt", "noun", "Sweet plant food", "Fruit is nutritious."),
            ("vegetable", "sebze", "ˈvedʒtəbl", "noun", "Plant food", "Vegetables are healthy."),
            ("egg", "yumurta", "eɡ", "noun", "Chicken product", "Eggs for breakfast."),
            ("milk", "süt", "mɪlk", "noun", "Dairy drink", "Milk is white."),
            ("water", "su", "ˈwɔːtə", "noun", "Clear liquid", "Water is essential."),
            ("coffee", "kahve", "ˈkɒfi", "noun", "Hot drink", "Coffee in the morning."),
            ("tea", "çay", "tiː", "noun", "Hot drink", "Tea with lemon."),
        ],
        "Hobbies": [
            ("reading", "okumak", "ˈriːdɪŋ", "noun", "Looking at text", "Reading is relaxing."),
            ("swimming", "yüzmek", "ˈswɪmɪŋ", "noun", "Moving in water", "Swimming is good exercise."),
            ("running", "koşmak", "ˈrʌnɪŋ", "noun", "Fast movement", "Running keeps fit."),
            ("cooking", "yemek yapmak", "ˈkʊkɪŋ", "noun", "Preparing food", "Cooking is creative."),
            ("painting", "resim yapmak", "ˈpeɪntɪŋ", "noun", "Making art", "Painting is therapeutic."),
            ("dancing", "dans etmek", "ˈdɑːnsɪŋ", "noun", "Moving to music", "Dancing is fun."),
            ("singing", "şarkı söylemek", "ˈsɪŋɪŋ", "noun", "Making music with voice", "Singing makes happy."),
            ("photography", "fotoğrafçılık", "fəˈtɒɡrəfi", "noun", "Taking pictures", "Photography captures moments."),
            ("gardening", "bahçecilik", "ˈɡɑːdnɪŋ", "noun", "Growing plants", "Gardening is peaceful."),
            ("traveling", "seyahat etmek", "ˈtrævlɪŋ", "noun", "Visiting places", "Traveling broadens mind."),
        ],
        "Transportation": [
            ("car", "araba", "kɑː", "noun", "Vehicle with four wheels", "My car is blue."),
            ("bus", "otobüs", "bʌs", "noun", "Public vehicle", "Bus arrives at 8."),
            ("train", "tren", "treɪn", "noun", "Railway vehicle", "Train is fast."),
            ("bicycle", "bisiklet", "ˈbaɪsɪkl", "noun", "Two-wheel vehicle", "Bicycle is eco-friendly."),
            ("motorcycle", "motosiklet", "ˈməʊtəsaɪkl", "noun", "Motorized two-wheeler", "Motorcycle is quick."),
            ("airplane", "uçak", "ˈeəpleɪn", "noun", "Flying vehicle", "Airplane flies high."),
            ("boat", "tekne", "bəʊt", "noun", "Water vehicle", "Boat floats on water."),
            ("ship", "gemi", "ʃɪp", "noun", "Large boat", "Ship crosses ocean."),
            ("taxi", "taksi", "ˈtæksi", "noun", "Hired car", "Taxi takes you anywhere."),
            ("subway", "metro", "ˈsʌbweɪ", "noun", "Underground train", "Subway is underground."),
        ],
    },
    "B1": {
        "Abstract": [
            ("freedom", "özgürlük", "ˈfriːdəm", "noun", "State of being free", "Freedom is important."),
            ("justice", "adalet", "ˈdʒʌstɪs", "noun", "Fairness", "Justice must prevail."),
            ("knowledge", "bilgi", "ˈnɒlɪdʒ", "noun", "Information", "Knowledge is power."),
            ("wisdom", "bilgelik", "ˈwɪzdəm", "noun", "Deep understanding", "Wisdom comes with age."),
            ("courage", "cesaret", "ˈkʌrɪdʒ", "noun", "Bravery", "Courage helps overcome fear."),
            ("patience", "sabır", "ˈpeɪʃns", "noun", "Ability to wait", "Patience is a virtue."),
            ("honesty", "dürüstlük", "ˈɒnɪsti", "noun", "Truthfulness", "Honesty builds trust."),
            ("respect", "saygı", "rɪˈspekt", "noun", "Admiration", "Respect is mutual."),
            ("responsibility", "sorumluluk", "rɪˌspɒnsəˈbɪləti", "noun", "Duty", "Responsibility teaches maturity."),
            ("success", "başarı", "səkˈses", "noun", "Achievement", "Success requires hard work."),
            ("opportunity", "fırsat", "ˌɒpəˈtjuːnəti", "noun", "Favorable chance", "Opportunity knocks once."),
            ("challenge", "zorluk", "ˈtʃælɪndʒ", "noun", "Difficult task", "Challenge makes stronger."),
            ("experience", "deneyim", "ɪkˈspɪəriəns", "noun", "Knowledge from doing", "Experience teaches lessons."),
            ("progress", "ilerleme", "ˈprəʊɡres", "noun", "Moving forward", "Progress takes time."),
            ("improvement", "gelişme", "ɪmˈpruːvmənt", "noun", "Getting better", "Improvement is constant."),
        ],
        "Technology": [
            ("computer", "bilgisayar", "kəmˈpjuːtə", "noun", "Electronic device", "Computer helps work."),
            ("internet", "internet", "ˈɪntənet", "noun", "Global network", "Internet connects world."),
            ("smartphone", "akıllı telefon", "ˈsmɑːtfəʊn", "noun", "Mobile device", "Smartphone is essential."),
            ("application", "uygulama", "ˌæplɪˈkeɪʃn", "noun", "Software program", "Application is useful."),
            ("website", "web sitesi", "ˈwebsaɪt", "noun", "Online page", "Website provides information."),
            ("email", "e-posta", "ˈiːmeɪl", "noun", "Electronic mail", "Email is quick."),
            ("password", "şifre", "ˈpɑːswɜːd", "noun", "Secret code", "Password must be strong."),
            ("software", "yazılım", "ˈsɒftweə", "noun", "Computer programs", "Software updates regularly."),
            ("hardware", "donanım", "ˈhɑːdweə", "noun", "Physical equipment", "Hardware needs maintenance."),
            ("data", "veri", "ˈdeɪtə", "noun", "Information", "Data is valuable."),
            ("network", "ağ", "ˈnetwɜːk", "noun", "Connected system", "Network is secure."),
            ("screen", "ekran", "skriːn", "noun", "Display surface", "Screen is bright."),
            ("keyboard", "klavye", "ˈkiːbɔːd", "noun", "Input device", "Keyboard is wireless."),
            ("mouse", "fare", "maʊs", "noun", "Pointing device", "Mouse clicks smoothly."),
            ("download", "indirmek", "ˈdaʊnləʊd", "verb", "Save from internet", "Download takes time."),
        ],
        "Business": [
            ("company", "şirket", "ˈkʌmpəni", "noun", "Business organization", "Company grows quickly."),
            ("employee", "çalışan", "ɪmˈplɔɪiː", "noun", "Worker", "Employee works hard."),
            ("employer", "işveren", "ɪmˈplɔɪə", "noun", "Boss", "Employer pays salary."),
            ("salary", "maaş", "ˈsæləri", "noun", "Payment for work", "Salary is monthly."),
            ("meeting", "toplantı", "ˈmiːtɪŋ", "noun", "Gathering", "Meeting starts soon."),
            ("project", "proje", "ˈprɒdʒekt", "noun", "Planned work", "Project deadline approaches."),
            ("deadline", "son tarih", "ˈdedlaɪn", "noun", "Time limit", "Deadline is tomorrow."),
            ("contract", "sözleşme", "ˈkɒntrækt", "noun", "Agreement", "Contract is signed."),
            ("customer", "müşteri", "ˈkʌstəmə", "noun", "Buyer", "Customer is satisfied."),
            ("product", "ürün", "ˈprɒdʌkt", "noun", "Item for sale", "Product sells well."),
            ("service", "hizmet", "ˈsɜːvɪs", "noun", "Help provided", "Service is excellent."),
            ("profit", "kar", "ˈprɒfɪt", "noun", "Money earned", "Profit increases yearly."),
            ("loss", "zarar", "lɒs", "noun", "Money lost", "Loss is unexpected."),
            ("investment", "yatırım", "ɪnˈvestmənt", "noun", "Money put in", "Investment pays off."),
            ("market", "pazar", "ˈmɑːkɪt", "noun", "Place of trade", "Market is competitive."),
        ],
        "Education": [
            ("university", "üniversite", "ˌjuːnɪˈvɜːsəti", "noun", "Higher education", "University offers degrees."),
            ("degree", "derece", "dɪˈɡriː", "noun", "Academic qualification", "Degree is valuable."),
            ("subject", "konu", "ˈsʌbdʒɪkt", "noun", "Area of study", "Subject is interesting."),
            ("exam", "sınav", "ɪɡˈzæm", "noun", "Test", "Exam is difficult."),
            ("grade", "not", "ɡreɪd", "noun", "Score", "Grade is high."),
            ("homework", "ödev", "ˈhəʊmwɜːk", "noun", "School work at home", "Homework is due."),
            ("assignment", "görev", "əˈsaɪnmənt", "noun", "Given task", "Assignment is challenging."),
            ("lecture", "ders", "ˈlektʃə", "noun", "Educational talk", "Lecture is informative."),
            ("research", "araştırma", "rɪˈsɜːtʃ", "noun", "Study investigation", "Research takes years."),
            ("scholarship", "burs", "ˈskɒləʃɪp", "noun", "Financial aid", "Scholarship helps students."),
            ("certificate", "sertifika", "səˈtɪfɪkət", "noun", "Proof of achievement", "Certificate is earned."),
            ("course", "kurs", "kɔːs", "noun", "Series of lessons", "Course is comprehensive."),
            ("training", "eğitim", "ˈtreɪnɪŋ", "noun", "Learning process", "Training improves skills."),
            ("skill", "beceri", "skɪl", "noun", "Ability", "Skill develops over time."),
            ("knowledge", "bilgi", "ˈnɒlɪdʒ", "noun", "Understanding", "Knowledge is essential."),
        ],
        "Health": [
            ("medicine", "ilaç", "ˈmedsn", "noun", "Drug for treatment", "Medicine helps recovery."),
            ("treatment", "tedavi", "ˈtriːtmənt", "noun", "Medical care", "Treatment is effective."),
            ("disease", "hastalık", "dɪˈziːz", "noun", "Illness", "Disease needs attention."),
            ("symptom", "semptom", "ˈsɪmptəm", "noun", "Sign of illness", "Symptom is mild."),
            ("diagnosis", "teşhis", "ˌdaɪəɡˈnəʊsɪs", "noun", "Identification of illness", "Diagnosis is accurate."),
            ("surgery", "ameliyat", "ˈsɜːdʒəri", "noun", "Medical operation", "Surgery is scheduled."),
            ("patient", "hasta", "ˈpeɪʃnt", "noun", "Sick person", "Patient is recovering."),
            ("appointment", "randevu", "əˈpɔɪntmənt", "noun", "Scheduled meeting", "Appointment is tomorrow."),
            ("prescription", "reçete", "prɪˈskrɪpʃn", "noun", "Medical order", "Prescription is filled."),
            ("vaccine", "aşı", "vækˈsiːn", "noun", "Preventive medicine", "Vaccine protects health."),
            ("exercise", "egzersiz", "ˈeksəsaɪz", "noun", "Physical activity", "Exercise keeps healthy."),
            ("diet", "diyet", "ˈdaɪət", "noun", "Food plan", "Diet is balanced."),
            ("nutrition", "beslenme", "njuːˈtrɪʃn", "noun", "Food intake", "Nutrition is important."),
            ("vitamin", "vitamin", "ˈvɪtəmɪn", "noun", "Essential nutrient", "Vitamin supports health."),
            ("fitness", "kondisyon", "ˈfɪtnəs", "noun", "Physical condition", "Fitness improves gradually."),
        ],
    },
    "B2": {
        "Advanced_Concepts": [
            ("sustainability", "sürdürülebilirlik", "səˌsteɪnəˈbɪləti", "noun", "Long-term viability", "Sustainability is crucial."),
            ("innovation", "yenilik", "ˌɪnəˈveɪʃn", "noun", "New ideas", "Innovation drives progress."),
            ("diversity", "çeşitlilik", "daɪˈvɜːsəti", "noun", "Variety", "Diversity enriches culture."),
            ("collaboration", "işbirliği", "kəˌlæbəˈreɪʃn", "noun", "Working together", "Collaboration achieves goals."),
            ("efficiency", "verimlilik", "ɪˈfɪʃnsi", "noun", "Effectiveness", "Efficiency saves time."),
            ("productivity", "üretkenlik", "ˌprɒdʌkˈtɪvəti", "noun", "Output rate", "Productivity increases."),
            ("creativity", "yaratıcılık", "ˌkriːeɪˈtɪvəti", "noun", "Imaginative ability", "Creativity solves problems."),
            ("leadership", "liderlik", "ˈliːdəʃɪp", "noun", "Guidance ability", "Leadership inspires others."),
            ("communication", "iletişim", "kəˌmjuːnɪˈkeɪʃn", "noun", "Information exchange", "Communication is key."),
            ("negotiation", "müzakere", "nɪˌɡəʊʃiˈeɪʃn", "noun", "Discussion for agreement", "Negotiation requires skill."),
        ],
        "Environment": [
            ("climate", "iklim", "ˈklaɪmət", "noun", "Weather patterns", "Climate is changing."),
            ("pollution", "kirlilik", "pəˈluːʃn", "noun", "Contamination", "Pollution harms environment."),
            ("recycling", "geri dönüşüm", "ˌriːˈsaɪklɪŋ", "noun", "Reusing materials", "Recycling helps planet."),
            ("conservation", "koruma", "ˌkɒnsəˈveɪʃn", "noun", "Protection", "Conservation saves resources."),
            ("renewable", "yenilenebilir", "rɪˈnjuːəbl", "adjective", "Can be replaced", "Renewable energy is clean."),
            ("ecosystem", "ekosistem", "ˈiːkəʊsɪstəm", "noun", "Natural system", "Ecosystem is balanced."),
            ("biodiversity", "biyoçeşitlilik", "ˌbaɪəʊdaɪˈvɜːsəti", "noun", "Life variety", "Biodiversity is vital."),
            ("habitat", "yaşam alanı", "ˈhæbɪtæt", "noun", "Living environment", "Habitat is threatened."),
            ("endangered", "nesli tehlikede", "ɪnˈdeɪndʒəd", "adjective", "At risk", "Endangered species need protection."),
            ("emission", "emisyon", "ɪˈmɪʃn", "noun", "Released substance", "Emission must decrease."),
        ],
    }
}

# Spanish Vocabulary
SPANISH_VOCABULARY = {
    "A1": {
        "Basic": [
            ("hola", "merhaba", "ˈola", "interjection", "Hello", "¡Hola! ¿Cómo estás?"),
            ("adiós", "güle güle", "aˈðjos", "interjection", "Goodbye", "Adiós, hasta luego."),
            ("gracias", "teşekkürler", "ˈɡɾasjas", "interjection", "Thank you", "Muchas gracias."),
            ("por favor", "lütfen", "poɾ faˈβoɾ", "phrase", "Please", "Por favor, ayúdame."),
            ("sí", "evet", "si", "adverb", "Yes", "Sí, estoy de acuerdo."),
            ("no", "hayır", "no", "adverb", "No", "No, gracias."),
        ],
        "Numbers": [
            ("uno", "bir", "ˈuno", "number", "One", "Tengo un libro."),
            ("dos", "iki", "dos", "number", "Two", "Dos personas."),
            ("tres", "üç", "tɾes", "number", "Three", "Tres días."),
            ("cuatro", "dört", "ˈkwatɾo", "number", "Four", "Cuatro semanas."),
            ("cinco", "beş", "ˈθinko", "number", "Five", "Cinco minutos."),
            ("seis", "altı", "sejs", "number", "Six", "Seis meses."),
            ("siete", "yedi", "ˈsjete", "number", "Seven", "Siete años."),
            ("ocho", "sekiz", "ˈotʃo", "number", "Eight", "Ocho horas."),
            ("nueve", "dokuz", "ˈnweβe", "number", "Nine", "Nueve estudiantes."),
            ("diez", "on", "djeθ", "number", "Ten", "Diez dedos."),
        ],
        "Colors": [
            ("rojo", "kırmızı", "ˈroxo", "adjective", "Red", "Un coche rojo."),
            ("azul", "mavi", "aˈθul", "adjective", "Blue", "El cielo azul."),
            ("verde", "yeşil", "ˈbeɾðe", "adjective", "Green", "Hierba verde."),
            ("amarillo", "sarı", "amaˈɾiʎo", "adjective", "Yellow", "Flores amarillas."),
            ("negro", "siyah", "ˈneɣɾo", "adjective", "Black", "Café negro."),
            ("blanco", "beyaz", "ˈblaŋko", "adjective", "White", "Nieve blanca."),
        ],
        "Family": [
            ("madre", "anne", "ˈmaðɾe", "noun", "Mother", "Mi madre es amable."),
            ("padre", "baba", "ˈpaðɾe", "noun", "Father", "Mi padre trabaja."),
            ("hermana", "kız kardeş", "eɾˈmana", "noun", "Sister", "Tengo una hermana."),
            ("hermano", "erkek kardeş", "eɾˈmano", "noun", "Brother", "Mi hermano es alto."),
            ("abuela", "büyükanne", "aˈβwela", "noun", "Grandmother", "Abuela cocina bien."),
            ("abuelo", "büyükbaba", "aˈβwelo", "noun", "Grandfather", "Abuelo cuenta historias."),
        ],
        "Animals": [
            ("perro", "köpek", "ˈpero", "noun", "Dog", "El perro es amigable."),
            ("gato", "kedi", "ˈɡato", "noun", "Cat", "El gato duerme."),
            ("pájaro", "kuş", "ˈpaxaɾo", "noun", "Bird", "El pájaro canta."),
            ("pez", "balık", "peθ", "noun", "Fish", "El pez nada."),
            ("caballo", "at", "kaˈβaʎo", "noun", "Horse", "El caballo corre."),
        ],
        "Food": [
            ("pan", "ekmek", "pan", "noun", "Bread", "Pan fresco."),
            ("agua", "su", "ˈaɣwa", "noun", "Water", "Agua fría."),
            ("leche", "süt", "ˈletʃe", "noun", "Milk", "Leche blanca."),
            ("café", "kahve", "kaˈfe", "noun", "Coffee", "Café caliente."),
            ("carne", "et", "ˈkaɾne", "noun", "Meat", "Carne cocida."),
            ("fruta", "meyve", "ˈfɾuta", "noun", "Fruit", "Fruta fresca."),
        ],
    },
    "A2": {
        "Jobs": [
            ("profesor", "öğretmen", "pɾofeˈsoɾ", "noun", "Teacher", "El profesor enseña."),
            ("médico", "doktor", "ˈmeðiko", "noun", "Doctor", "El médico ayuda."),
            ("enfermera", "hemşire", "enfeɾˈmeɾa", "noun", "Nurse", "La enfermera cuida."),
            ("ingeniero", "mühendis", "inxeˈnjeɾo", "noun", "Engineer", "El ingeniero diseña."),
            ("cocinero", "aşçı", "koθiˈneɾo", "noun", "Cook", "El cocinero prepara comida."),
        ],
        "Places": [
            ("escuela", "okul", "esˈkwela", "noun", "School", "Los niños van a la escuela."),
            ("hospital", "hastane", "ospiˈtal", "noun", "Hospital", "El hospital trata enfermos."),
            ("banco", "banka", "ˈbaŋko", "noun", "Bank", "El banco guarda dinero."),
            ("biblioteca", "kütüphane", "bibljoˈteka", "noun", "Library", "La biblioteca tiene libros."),
            ("parque", "park", "ˈpaɾke", "noun", "Park", "El parque tiene hierba."),
        ],
        "Emotions": [
            ("feliz", "mutlu", "feˈliθ", "adjective", "Happy", "Estoy feliz."),
            ("triste", "üzgün", "ˈtɾiste", "adjective", "Sad", "Ella está triste."),
            ("enojado", "kızgın", "enoˈxaðo", "adjective", "Angry", "Estoy enojado."),
            ("emocionado", "heyecanlı", "emoθjoˈnaðo", "adjective", "Excited", "Él está emocionado."),
            ("cansado", "yorgun", "kanˈsaðo", "adjective", "Tired", "Estoy cansado."),
        ],
    },
    "B1": {
        "Technology": [
            ("ordenador", "bilgisayar", "oɾðenaˈðoɾ", "noun", "Computer", "El ordenador ayuda."),
            ("internet", "internet", "inteɾˈnet", "noun", "Internet", "Internet conecta el mundo."),
            ("teléfono", "telefon", "teˈlefono", "noun", "Phone", "Mi teléfono es nuevo."),
            ("correo", "e-posta", "koˈreo", "noun", "Email", "Envío un correo."),
            ("aplicación", "uygulama", "aplikaˈθjon", "noun", "Application", "La aplicación es útil."),
        ],
        "Business": [
            ("empresa", "şirket", "emˈpɾesa", "noun", "Company", "La empresa crece."),
            ("empleado", "çalışan", "empleˈaðo", "noun", "Employee", "El empleado trabaja."),
            ("reunión", "toplantı", "rewˈnjon", "noun", "Meeting", "La reunión empieza."),
            ("proyecto", "proje", "pɾoˈʝekto", "noun", "Project", "El proyecto avanza."),
            ("cliente", "müşteri", "kliˈente", "noun", "Customer", "El cliente está satisfecho."),
        ],
    }
}

# French Vocabulary
FRENCH_VOCABULARY = {
    "A1": {
        "Basic": [
            ("bonjour", "merhaba", "bɔ̃ʒuʁ", "interjection", "Hello", "Bonjour! Comment allez-vous?"),
            ("au revoir", "güle güle", "o ʁəvwaʁ", "phrase", "Goodbye", "Au revoir, à bientôt."),
            ("merci", "teşekkürler", "mɛʁsi", "interjection", "Thank you", "Merci beaucoup."),
            ("s'il vous plaît", "lütfen", "sil vu plɛ", "phrase", "Please", "S'il vous plaît, aidez-moi."),
            ("oui", "evet", "wi", "adverb", "Yes", "Oui, je suis d'accord."),
            ("non", "hayır", "nɔ̃", "adverb", "No", "Non, merci."),
        ],
        "Numbers": [
            ("un", "bir", "œ̃", "number", "One", "J'ai un livre."),
            ("deux", "iki", "dø", "number", "Two", "Deux personnes."),
            ("trois", "üç", "tʁwa", "number", "Three", "Trois jours."),
            ("quatre", "dört", "katʁ", "number", "Four", "Quatre semaines."),
            ("cinq", "beş", "sɛ̃k", "number", "Five", "Cinq minutes."),
            ("six", "altı", "sis", "number", "Six", "Six mois."),
            ("sept", "yedi", "sɛt", "number", "Seven", "Sept ans."),
            ("huit", "sekiz", "ɥit", "number", "Eight", "Huit heures."),
            ("neuf", "dokuz", "nœf", "number", "Nine", "Neuf étudiants."),
            ("dix", "on", "dis", "number", "Ten", "Dix doigts."),
        ],
        "Colors": [
            ("rouge", "kırmızı", "ʁuʒ", "adjective", "Red", "Une voiture rouge."),
            ("bleu", "mavi", "blø", "adjective", "Blue", "Le ciel bleu."),
            ("vert", "yeşil", "vɛʁ", "adjective", "Green", "L'herbe verte."),
            ("jaune", "sarı", "ʒon", "adjective", "Yellow", "Des fleurs jaunes."),
            ("noir", "siyah", "nwaʁ", "adjective", "Black", "Café noir."),
            ("blanc", "beyaz", "blɑ̃", "adjective", "White", "Neige blanche."),
        ],
        "Family": [
            ("mère", "anne", "mɛʁ", "noun", "Mother", "Ma mère est gentille."),
            ("père", "baba", "pɛʁ", "noun", "Father", "Mon père travaille."),
            ("sœur", "kız kardeş", "sœʁ", "noun", "Sister", "J'ai une sœur."),
            ("frère", "erkek kardeş", "fʁɛʁ", "noun", "Brother", "Mon frère est grand."),
            ("grand-mère", "büyükanne", "ɡʁɑ̃mɛʁ", "noun", "Grandmother", "Grand-mère cuisine bien."),
            ("grand-père", "büyükbaba", "ɡʁɑ̃pɛʁ", "noun", "Grandfather", "Grand-père raconte des histoires."),
        ],
        "Animals": [
            ("chien", "köpek", "ʃjɛ̃", "noun", "Dog", "Le chien est amical."),
            ("chat", "kedi", "ʃa", "noun", "Cat", "Le chat dort."),
            ("oiseau", "kuş", "wazo", "noun", "Bird", "L'oiseau chante."),
            ("poisson", "balık", "pwasɔ̃", "noun", "Fish", "Le poisson nage."),
            ("cheval", "at", "ʃəval", "noun", "Horse", "Le cheval court."),
        ],
        "Food": [
            ("pain", "ekmek", "pɛ̃", "noun", "Bread", "Pain frais."),
            ("eau", "su", "o", "noun", "Water", "Eau froide."),
            ("lait", "süt", "lɛ", "noun", "Milk", "Lait blanc."),
            ("café", "kahve", "kafe", "noun", "Coffee", "Café chaud."),
            ("viande", "et", "vjɑ̃d", "noun", "Meat", "Viande cuite."),
            ("fruit", "meyve", "fʁɥi", "noun", "Fruit", "Fruit frais."),
        ],
    },
    "A2": {
        "Jobs": [
            ("professeur", "öğretmen", "pʁɔfesœʁ", "noun", "Teacher", "Le professeur enseigne."),
            ("médecin", "doktor", "medsɛ̃", "noun", "Doctor", "Le médecin aide."),
            ("infirmière", "hemşire", "ɛ̃fiʁmjɛʁ", "noun", "Nurse", "L'infirmière soigne."),
            ("ingénieur", "mühendis", "ɛ̃ʒenjœʁ", "noun", "Engineer", "L'ingénieur conçoit."),
            ("cuisinier", "aşçı", "kɥizinje", "noun", "Cook", "Le cuisinier prépare."),
        ],
        "Places": [
            ("école", "okul", "ekɔl", "noun", "School", "Les enfants vont à l'école."),
            ("hôpital", "hastane", "opital", "noun", "Hospital", "L'hôpital soigne les malades."),
            ("banque", "banka", "bɑ̃k", "noun", "Bank", "La banque garde l'argent."),
            ("bibliothèque", "kütüphane", "biblijɔtɛk", "noun", "Library", "La bibliothèque a des livres."),
            ("parc", "park", "paʁk", "noun", "Park", "Le parc a de l'herbe."),
        ],
        "Emotions": [
            ("heureux", "mutlu", "œʁø", "adjective", "Happy", "Je suis heureux."),
            ("triste", "üzgün", "tʁist", "adjective", "Sad", "Elle est triste."),
            ("fâché", "kızgın", "faʃe", "adjective", "Angry", "Je suis fâché."),
            ("excité", "heyecanlı", "ɛksite", "adjective", "Excited", "Il est excité."),
            ("fatigué", "yorgun", "fatiɡe", "adjective", "Tired", "Je suis fatigué."),
        ],
    },
    "B1": {
        "Technology": [
            ("ordinateur", "bilgisayar", "ɔʁdinatœʁ", "noun", "Computer", "L'ordinateur aide."),
            ("internet", "internet", "ɛ̃tɛʁnɛt", "noun", "Internet", "Internet connecte le monde."),
            ("téléphone", "telefon", "telefɔn", "noun", "Phone", "Mon téléphone est nouveau."),
            ("courriel", "e-posta", "kuʁjɛl", "noun", "Email", "J'envoie un courriel."),
            ("application", "uygulama", "aplikasjɔ̃", "noun", "Application", "L'application est utile."),
        ],
        "Business": [
            ("entreprise", "şirket", "ɑ̃tʁəpʁiz", "noun", "Company", "L'entreprise grandit."),
            ("employé", "çalışan", "ɑ̃plwaje", "noun", "Employee", "L'employé travaille."),
            ("réunion", "toplantı", "ʁeynjɔ̃", "noun", "Meeting", "La réunion commence."),
            ("projet", "proje", "pʁɔʒɛ", "noun", "Project", "Le projet avance."),
            ("client", "müşteri", "klijɑ̃", "noun", "Customer", "Le client est satisfait."),
        ],
    }
}


def get_all_vocabulary():
    """Return all vocabulary organized by language and level"""
    return {
        "en": ENGLISH_VOCABULARY,
        "es": SPANISH_VOCABULARY,
        "fr": FRENCH_VOCABULARY,
    }
